# Constant colors and fonts using in this GUI
HEADER_FONT = ('Open Sans', 17)
BUTTON_FONT_LIGHT = ('Open Sans light', 13)
LABEL_FONT = ('Open Sans', 13)
LABEL_FONT_INFO = ('Open Sans light', 13)
LABEL_FONT_SMALL = ('Open Sans', 11)
ENTRY_FONT = ('Open Sans', 10)
STATUS_FONT = ('Open Sans Bold', 20)
STATUS_FONT_LIGHT = ('Open Sans Light', 20)

BACKGROUND_COLOR_GRAY = '#434343'
BACKGROUND_COLOR_GRAY_DARKER = '#333333'
BUTTON_COLOR_GRAY = '#373739'
BUTTON_COLOR_GRAY_ACTIVE = '#353535'
BUTTON_COLOR_GRAY_PRESSED = '#313131'
BUTTON_COLOR_LIGHT = '#F4F4F4'
SUCCESS_COLOR = '#55C621'
WARNING_COLOR = '#EFC61C'
ERROR_COLOR = '#FC5753'

# Other settings
DEBUG = True
KEY_SIZE = 1024
